### ISSUE TITLE
`pip install verify` installs incompatible version of pydash

### ISSUE THREAD

**Issue by ollanta** [dgilland/verify#10]
Installing `verify` with pip will install the latest version of pydash (the requirement is `>=3.2.2`), but since `pydash` version 4.0.0, `pydash.is_int` no longer exists ([ref](https://github.com/dgilland/pydash/blob/1e8e78a233ed5395316bf61e8ffc21ec5da11953/pydash/predicates.py#L740)). This breaks verify in some places ([here for example](https://github.com/dgilland/verify/blob/a2693862e04e6ccd5f72264910d46004219782c9/verify/types.py#L342)) breaking fresh installs.

**Comment by dgilland** [comment]
Fixed in `v1.1.1`: https://pypi.python.org/pypi/verify/1.1.1
